# Generated by Django 3.1.3 on 2022-02-21 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='membership',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.TextField(max_length=10)),
                ('userCar', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='driveapp.membership')),
            ],
        ),
        migrations.CreateModel(
            name='prod',
            fields=[
                ('prodID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.TextField(max_length=10)),
                ('prodName', models.TextField(max_length=10)),
                ('prodImage', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='prodOptionDetail',
            fields=[
                ('prodOptionDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('prodID', models.ForeignKey(db_column='prodID', on_delete=django.db.models.deletion.CASCADE, to='driveapp.prod')),
            ],
        ),
        migrations.CreateModel(
            name='orderDetail',
            fields=[
                ('orderdetailID', models.AutoField(primary_key=True, serialize=False)),
                ('orderID', models.ForeignKey(db_column='orderID', on_delete=django.db.models.deletion.CASCADE, to='driveapp.order')),
                ('prodID', models.ForeignKey(db_column='prodID', on_delete=django.db.models.deletion.CASCADE, to='driveapp.prod')),
            ],
        ),
    ]
