# Generated by Django 3.1.3 on 2022-03-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cafe',
            fields=[
                ('managerPassword', models.IntegerField(primary_key=True, serialize=False)),
                ('staffPassword', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='prods',
            fields=[
                ('prodID', models.AutoField(primary_key=True, serialize=False)),
                ('prodCategory', models.TextField(max_length=10)),
                ('prodName', models.TextField(max_length=10)),
                ('prodPrice', models.IntegerField()),
                ('prodImage', models.ImageField(blank=True, upload_to='')),
                ('prodRecommed', models.BooleanField()),
                ('prodHotOrCold', models.IntegerField()),
                ('prodCafAmount', models.BooleanField()),
                ('prodSyrup', models.IntegerField()),
                ('prodShot', models.BooleanField()),
                ('prodMilk', models.BooleanField()),
                ('prodWhip', models.BooleanField()),
                ('prodJavaChip', models.BooleanField()),
                ('prodDriz', models.BooleanField()),
                ('prodSalesRate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userCar', models.TextField(max_length=10)),
                ('userName', models.TextField(max_length=10)),
                ('membership', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderPrice', models.IntegerField()),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='driveapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemQuantity', models.IntegerField()),
                ('itemSize', models.IntegerField()),
                ('itemPrice', models.IntegerField()),
                ('itemHotOrCold', models.IntegerField()),
                ('itemCafAmount', models.IntegerField()),
                ('itemSyrup', models.IntegerField()),
                ('itemShot', models.IntegerField()),
                ('itemMilk', models.IntegerField()),
                ('itemWhip', models.IntegerField()),
                ('itemJavaChip', models.IntegerField()),
                ('itemDriz', models.IntegerField()),
                ('orderID', models.ForeignKey(db_column='orderID', on_delete=django.db.models.deletion.CASCADE, to='driveapp.orders')),
                ('prodID', models.ForeignKey(db_column='prodID', on_delete=django.db.models.deletion.CASCADE, to='driveapp.prods')),
            ],
        ),
    ]
